env:
  browser: true
  es2021: true
  mocha: true
extends:
  - "plugin:react/recommended"
  - standard
parserOptions:
  ecmaVersion: 12
  sourceType: module
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: true
parser: babel-eslint
plugins:
  - react
rules:
  @emotion/pkg-renaming: error
  react/react-in-jsx-scope: off
  react/jsx-uses-react: off
  react/jsx-uses-vars: error
  react/jsx-closing-bracket-location:
    - 1
    - after-props
  react/jsx-indent-props:
    - error
    - 2
  react/jsx-first-prop-new-line:
    - error
    - multiline
  react/jsx-props-no-multi-spaces:
    - error
  space-infix-ops: error
  array-bracket-spacing:
    - error
    - never
  object-curly-spacing:
    - error
    - always
  keyword-spacing:
    - error
  space-before-function-paren:
    - error
  no-console:
    - error
  no-unused-vars:
    - error
    - ignoreRestSiblings: true
  no-multi-spaces:
    - error
  newline-after-var:
    - error
  indent:
    - error
    - 2
    - SwitchCase: 1
  linebreak-style:
    - off
    - windows
  quotes:
    - error
    - single
  semi:
    - error
    - never
  max-len:
    - error
    - 120
    - ignoreComments: true
      ignoreUrls: true
      ignoreRegExpLiterals: true
  padding-line-between-statements:
    - error
    - blankLine: always
      prev:
        - const
        - let
        - var
      next: "*"
    - blankLine: any
      prev:
        - const
        - let
        - var
      next:
        - const
        - let
        - var
    - blankLine: always
      prev: block-like
      next: "*"
    - blankLine: any
      prev: case
      next: "*"
